Repository jgthms/bulma, pull requests merged in 2018-05, with the labels that each got.

#1884 Fixes issue #753
  docs/_data/variables/components/navbar.json
  sass/components/navbar.sass
Labels: good contribution

#1749 Fix icons floating out of input area
  sass/elements/form.sass
Labels: in review

#1679 Add breakpoint based column gaps
  sass/grid/columns.sass
Labels: good contribution, needs work
