Repository jgthms/bulma, pull requests merged in 2018-10, with the labels that each got.

#1982 Fix navbar-burger color when color modifier is used
  sass/components/navbar.sass
Labels: needs work

#1744 Update table.sass, fix color hover on striped rows [Fix #1710]
  sass/elements/table.sass
Labels: in review

#1819 fix error message for required file fix #1137
  sass/elements/form.sass
Labels: in review

#1926 Update extensions.html to include bulma-o-steps
  docs/extensions.html
  docs/images/bulma-o-steps.png
  docs/images/extensions/bulma-o-steps.png
Labels: needs work

#1978 The Details disclosure element fixes
  sass/elements/form.sass
Labels: needs work

#2195 improvement - Bring code-example as readable HTML
  docs/documentation/columns/nesting.html
Labels: needs work

#2206 add variables for setting background-color thead, tbody, tfoot
  CHANGELOG.md
  sass/elements/table.sass
Labels: good contribution

#2188 #2091 remove css rule which causes has-addons to not work correctly
  sass/elements/tag.sass
Labels: needs work

#592 Give arbitrary elements access to the image/ratio classes
  sass/elements/image.sass
Labels: good contribution, needs work
